Btn_AddCarrinho = "id:add-to-cart-button"
Btn_AddCartao = "id:pp-K6cJ42-68-announce"
Btn_ConfirmPedido = "id:placeYourOrder"
Btn_Continuar = "id:continue"
Btn_ContinuePedido = "css=input[name='ppw-widgetEvent:SetPaymentPlanSelectContinueEvent']"
Btn_FazerLogin = "id:signInSubmit"
Btn_FecharPedido = "css=input[name='proceedToRetailCheckout']"
Btn_IrCarrinho = "(//a[contains(text(),'Ir para o carrinho')])[2]"
Btn_Login = "//span[contains(text(),'Faça seu login')]"
Btn_UsarEndereco = "css=input[aria-labelledby='address-ui-widgets-form-submit-button-announce']"
Ico_Boleto = "css=img[class='pmts-boleto-icon-img']"
Ico_Loading = "id:first-pipeline-load-page-spinner-img"
Ico_Lupa = "id:nav-search-submit-button"
Ico_Pix = "css=img[class='pmts-pix-icon-img']"
Lbl_Adicionado = "//span[contains(text(),'Adicionado ao carrinho')]"
Lbl_CarrinhoVazio = "//h1[contains(text(),'Seu carrinho de compras da Amazon está vazio.')]"
Lbl_CheckPrice = "css=span[class='a-size-medium a-color-base sc-price sc-white-space-nowrap']"
Lbl_Contas = "id:nav-link-accountList"
Lbl_Disponivel = "css=span[class='a-size-base a-color-base s-underline-text']"
Lbl_Preco = "//span[@class='a-price-whole']"
Lbl_PrecoUnico = "//following::span[@class='a-price-whole']"
Lbl_Produto = "//span[./text()='PRODUTO']"
Lbl_SubTotal = "id:sc-subtotal-label-activecart"
Lbl_Voltar = "css=span[class='navFooterBackToTopText']"
Lnk_ComeceAqui = "//a[contains(text(),'Comece aqui.')]"
Lnk_ExcluirProduto = "css=input[value='Excluir']"
Lnk_IrCarrinho = "(//a[contains(text(),'Ir para o carrinho')])[2]"
Lnk_SubMenu = "//span[contains(text(),'SUBMENU')]//parent::a"
Opt_Menu = "//a[./text()='MENU']"
Opt_Opcao = "//span[@dir='auto' and contains(text(),'OPCAO')]"
Txt_Busca = "id:twotabsearchtextbox"
Txt_Cep = "id:address-ui-widgets-enterAddressPostalCode"
Txt_Email = "id:ap_email"
Txt_Endereco = "id:address-ui-widgets-streetName"
Txt_Nome = "id:ap_customer_name"
Txt_RepeatSenha = "id:ap_password_check"
Txt_ResComplemento = "id:address-ui-widgets-complement"
Txt_ResNumero = "id:address-ui-widgets-buildingNumber"
Txt_Senha = "id:ap_password"
Txt_Telefone = "id:address-ui-widgets-enterAddressPhoneNumber"